FROM python:3.12-slim AS builder
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

#only copying src/main/python/movie_lens_ranker.  see .dockerignore
COPY ./src ./src
COPY ./pyproject.toml ./
COPY ./requirements.txt ./

RUN chown -R 1000:1000 /app

RUN python3 -m pip install --no-cache-dir -c requirements.txt . --prefix=/usr/local
#update equinox from 0.11.7 to a version which uses jax.extend.core where needed:
RUN python3 -m pip install --no-cache-dir equinox==0.13.2 alembic==1.18.4 --prefix=/usr/local

#RUN python3 -m pip list

#check:
#RUN python3 -c "import jax; print('JAX version:', jax.__version__)"
#RUN python3 -c "import sys; print('SYS PATH:', sys.path); import site; print('SITE PACKAGES:', site.getsitepackages())"
#['', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/usr/local/lib/python3.12/site-packages']

ENTRYPOINT ["python3", "-m", "movie_lens_ranker.app_runner"]
#default flags go here:
#CMD ["param1","param2"] ...
