FROM python:3.12-slim

RUN pip install --no-cache-dir "google-vizier[jax]==0.1.24" psycopg2-binary==2.9.12 sqlalchemy==2.0.49 equinox==0.13.2

WORKDIR /app

EXPOSE 8080

COPY run_vizier_server.py .

RUN mkdir -p /data
RUN touch /data/vizier.db

CMD ["python3", "run_vizier_server.py"]
