FROM python:3.12-slim AS builder
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir --upgrade pip==24.0 setuptools==69.0.0 wheel==0.42.0

WORKDIR /app

COPY requirements-gpu.txt ./
RUN chown -R 1000:1000 /app

RUN python3 -m pip install --no-deps --no-cache-dir -r requirements-gpu.txt --prefix=/usr/local

#only copying src/main/python/movie_lens_ranker.  see .dockerignore
COPY ./src ./src
COPY ./pyproject.toml ./

RUN chown -R 1000:1000 /app

RUN python3 -m pip install --no-deps --no-cache-dir . --prefix=/usr/local

#check:
#RUN python3 -c "import jax; print('JAX version:', jax.__version__)"
#RUN python3 -c "import sys; print('SYS PATH:', sys.path); import site; print('SITE PACKAGES:', site.getsitepackages())"
#['', '/usr/local/lib/python312.zip', '/usr/local/lib/python3.12', '/usr/local/lib/python3.12/lib-dynload', '/usr/local/lib/python3.12/site-packages']

ENTRYPOINT ["python3", "-m", "movie_lens_ranker.app_runner"]
#default flags go here:
#CMD ["param1","param2"] ...
