include:
   - path: ./docker-compose-dbs.yaml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_cpu
    container_name: run_optuna_trial_train_fn
    depends_on:
      db:
        condition: service_healthy
      gcs:
        condition: service_healthy
    env_file:
      - .env
    environment:
      #these are in .env
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - TENSORSTORE_GCS_HTTP_ENDPOINT=${TENSORSTORE_GCS_HTTP_ENDPOINT}
      - STORAGE_EMULATOR_HOST=${STORAGE_EMULATOR_HOST}
      - CLOUD_STORAGE_EMULATOR_HOST=${CLOUD_STORAGE_EMULATOR_HOST}
      - CLOUD_STORAGE_EMULATOR_ENDPOINT=${CLOUD_STORAGE_EMULATOR_ENDPOINT}
      - TENSORSTORE_GCS_NO_AUTH=${TENSORSTORE_GCS_NO_AUTH}
      - NO_GCE_CHECK=${NO_GCE_CHECK}
      - GCS_LAMBDA_TOKEN=${GCS_LAMBDA_TOKEN}
      - GOOGLE_AUTH_SUPPRESS_CREDENTIALS_WARNINGS=${GOOGLE_AUTH_SUPPRESS_CREDENTIALS_WARNINGS}
      - STORAGE_EMULATOR_HOST_HTTP=${STORAGE_EMULATOR_HOST_HTTP}
      - GOOGLE_AUTH_EXTERNAL_ACCOUNT_TOKEN_PROHIBIT=${GOOGLE_AUTH_EXTERNAL_ACCOUNT_TOKEN_PROHIBIT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
