FROM python:3.12-slim

WORKDIR /app

COPY ./requirements_vizier.txt ./
COPY run_vizier_server.py .

RUN pip install --no-cache-dir "google-vizier[jax]==0.1.24" psycopg2-binary==2.9.12 sqlalchemy==2.0.49 -c requirements_vizier.txt
RUN pip install --no-cache-dir equinox==0.13.2

RUN mkdir -p ./data && touch ./data/vizier.db && chown -R 1000:1000 ./data

#USER 1000
EXPOSE 8080

CMD ["python3", "run_vizier_server.py"]
