#replace with SecretManager or tokens.  this file is committed to git for dev convenience
apiVersion: v1
kind: Secret
metadata:
  name: GraphRanker-db-credentials
type: Opaque
stringData:
  username: "runner"
  password: "password123"
