// proto/recommender.proto
syntax = "proto3";
package recommender;

// input for the query model

// input requests identifying a list of user and time, supplemented with demographic information
message UserRequest {
  repeated int64 user_ids = 1;
  repeated string genders = 2;
  repeated int64 occupations = 3;
  repeated int64 ages = 4;
  repeated int64 timestamp = 5;
  int32 n_users = 6;
}

// input for the graph ranker model

// The output from your orchestrator containing parallel vectors of movie_ids and their model scores
message RankedMovies {
  repeated int32 movie_ids = 1; // "repeated" means it's a Vec in Rust
  repeated float scores = 2;
  int64 user_id = 3;
}

message BatchRankedMovies {
  repeated RankedMovies user_rankings = 1;
}

// input request to return scored candidate_ids
message RankOnlyRequest {
  int32 user_id = 1;
  int64 timestamp = 2;
  repeated int32 candidate_ids = 3;
}

// Response message containing the user embedding and retrieved candidate IDs
message ApproxNearestNeighborsResponse {
  repeated float user_embedding = 1;
  repeated int32 candidate_ids = 2;
}

// methods available for the service
service RecommenderService {
  // request to retun top_k unwatched recommended movies for the user, descending order by score
  rpc Predict (UserRequest) returns (RankedMovies);
  // request to return the top_k of the candidate_ids in order of descending score
  rpc RankOnly(RankOnlyRequest) returns (RankedMovies);

  // request to return all of the candidate_ids, not reordered nor truncated
  rpc RankOnlyReturnAll(RankOnlyRequest) returns (RankedMovies);
  // request to return return nearest neigbhors of user embedding
  rpc ApproxNearestNeighbors(UserRequest) returns (ApproxNearestNeighborsResponse);

  // request to retun top_k unwatched recommended movies for the user, descending order by score
  rpc BatchPredict (BatchUserRequest) returns (BatchRankedMovies);
}