apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: graphranker-jax-training
  namespace: ranker-ns
spec:
  runtimeRef:
    name: jax-distributed
    apiGroup: trainer.kubeflow.org
    kind: ClusterTrainingRuntime
  trainer:
    # Define the size of your cluster (Replaces your StatefulSet replicas)
    numNodes: 2
    image: ranker-app:local
    args:
      - "--LOGNAME=runner"
      - "--USER=runner"
      - "--study_name=GraphRanker_tuning_kind"
      - "--mlflow_experiment_name=GraphRanker_tuning_kind"
      - "--mlflow_tracking_uri=postgresql://runner:password123@db-service:5432/mlflow_db"
      - "--vizier_endpoint=vizier-service:8000"
      - "--latest_checkpoint_uri=gs://checkpoint-bucket/latest"
      - "--best_checkpoint_uri=gs://checkpoint-bucket/best"
      - "--movies_uri=gs://data/movies-00000-of-00001.array_record"
      - "--recommendations_uri=gs://data/recommended_movies.array_record"
      - "--recommendations_ts_uri=gs://data/recommended_movies_timestamps.array_record"
      - "--ratings_train_uri=gs://data/small/ratings_train_liked.array_record"
      - "--ratings_val_uri=gs://data/small/ratings_val_liked.array_record"
      - "--train_negatives_uri=gs://data/train_negatives.array_record"
      - "--val_negatives_uri=gs://data/val_negatives.array_record"
      - "--movie_embeddings_uri=gs://data/movie_emb-00000-of-00001.array_record"
      - "--user_embeddings_uri=gs://data/user_emb-00000-of-00001.array_record"
      - "--num_epochs=2"
      - "--batch_size=64"
      - "--seed=12345"
      - "--phase=tune"
      - "--project_id=tune-kind-01"
      - "--grain_num_threads_fetching_records=2"
      - "--grain_num_threads_computing_num_records=2"
      - "--debug=True"
    #not allowed, so manually entering them in env
    #envFrom:
    #  - configMapRef:
    #      name: app-runner-env
    env:
      # trainer automatically injects MASTER_ADDR, MASTER_PORT, RANK,
      # WORLD_SIZE, LOCAL_RANK, LOCAL_SIZE
      # Downward API auto-injected metadata: annotation training.kubeflow.org/job-rank
      #     and Labels: Various jobset.x-k8s.io/*
      # Inject the exact Pod Name (e.g., 'app-runner-0') using Downward API
      - name: XLA_FLAGS
        value: "--xla_force_host_platform_device_count=2"
      - name: JAX_PROCESS_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['training.kubeflow.org/job-rank']
      - name: JAX_COORDINATOR_ADDRESS
        value: "graphranker-jax-training-master-0:8888" # Match the service name
      - name: JAX_NUM_PROCESSES
        value: "2"
      #for debugging:
      - name: ABSL_MIN_LOG_LEVEL
        value: "0"  # 0 is INFO, 1 is WARNING, 2 is ERROR, 3 is FATAL
      - name: GLOG_minloglevel
        value: "0"
      - name: TENSORSTORE_VERBOSE_LOGGING
        value: "1"
      #config map env vars because there is no envFrom
      - name: UID 
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: UID
      - name: GID 
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: GID
      - name: GOOGLE_CLOUD_PROJECT
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: GOOGLE_CLOUD_PROJECT
      - name: GCSFS_ENDPOINT_URL 
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: GCSFS_ENDPOINT_URL
      - name: TENSORSTORE_GCS_HTTP_URL
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: TENSORSTORE_GCS_HTTP_URL
      - name: STORAGE_EMULATOR_HOST
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: STORAGE_EMULATOR_HOST
      - name: CLOUD_STORAGE_EMULATOR_HOST
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: CLOUD_STORAGE_EMULATOR_HOST
      - name: CLOUD_STORAGE_EMULATOR_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: CLOUD_STORAGE_EMULATOR_ENDPOINT
      - name: TENSORSTORE_GCS_NO_AUTH
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: TENSORSTORE_GCS_NO_AUTH
      - name: NO_GCE_CHECK
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: NO_GCE_CHECK
      - name: GCS_LAMBDA_TOKEN
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: GCS_LAMBDA_TOKEN
      - name: GOOGLE_AUTH_SUPPRESS_CREDENTIALS_WARNINGS
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: GOOGLE_AUTH_SUPPRESS_CREDENTIALS_WARNINGS
      - name: STORAGE_EMULATOR_HOST_HTTP
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: STORAGE_EMULATOR_HOST_HTTP
      - name: GOOGLE_AUTH_EXTERNAL_ACCOUNT_TOKEN_PROHIBIT
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: GOOGLE_AUTH_EXTERNAL_ACCOUNT_TOKEN_PROHIBIT
      - name: GOOGLE_APPLICATION_CREDENTIALS
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: GOOGLE_APPLICATION_CREDENTIALS
      - name: TENSORSTORE_GCS_REQUEST_CONCURRENCY
        valueFrom:
          configMapKeyRef:
            name: app-runner-env
            key: TENSORSTORE_GCS_REQUEST_CONCURRENCY

  runtimePatches:
    - manager: "app-runner.patch/trainer" #domain-prefixed path such as acme.io/foo
      trainingRuntimeSpec:
        template:
          spec:
            replicatedJobs:
              - name: node
                template:
                  spec:
                    template:
                      spec:
                        containers:
                          - name: node
                            #imagePullPolicy: Never #<-- not recognized.  so use default behavior that an image:latest has default pull policy Always but an image tagged with anythin else other than latest has default policy IfNotPresent, so will make an image with tag :local for this
                            volumeMounts:
                              - name: source-code
                                mountPath: /app/src
                        volumes:
                          - name: source-code
                            hostPath:
                              path: /app/src
                              type: Directory

#debugging:
#kubectl get clustertrainingruntime jax-distributed -o yaml
#kubectl explain trainjob.spec.trainer
#kubectl explain trainjob.spec.runtimePatches.trainingRuntimeSpec
#kubectl explain trainjob.spec.runtimePatches.trainingRuntimeSpec.template.spec
# kubectl explain trainjob.spec.runtimePatches.trainingRuntimeSpec.template.spec.replicatedJobs.template.spec.template.spec.containers
