import os

import json

#=== these are so that grain dataloader can read data from fake gcs server running in docker ====
os.environ["STORAGE_EMULATOR_HOST"] = "http://127.0.0.1:4443"
os.environ["GOOGLE_CLOUD_PROJECT"] = "local-dev"
os.environ["GOOGLE_AUTH_EXTERNAL_ACCOUNT_TOKEN_PROHIBIT"] = "true"

# ==== these in addtion to above, are for orbax to read and write to fake_gcs_Server running in docker ====
# For the C++ GCS client (crucial for performance-heavy libs)
os.environ["CLOUD_STORAGE_EMULATOR_HOST"] = "http://127.0.0.1:4443"
# For TensorStore (Orbax uses this for sharded JAX arrays)
# Some versions of the C++ lib look for this specifically
os.environ["CLOUD_STORAGE_EMULATOR_ENDPOINT"] = "http://127.0.0.1:4443"
# Force the library to use HTTP instead of HTTPS
os.environ["STORAGE_EMULATOR_HOST_HTTP"] = "true"
# 4. Disable authentication checks that cause the 'wait'
os.environ["NO_GCE_CHECK"] = "true"
os.environ["GCS_LAMBDA_TOKEN"] = "none"

import os.path
import unittest

from array_record.python import array_record_module
from helper import *
from movie_lens_ranker.data_loading import *

from movie_lens_ranker.data_contracts import *


class TestDataContracts(unittest.TestCase):
    def setUp(self):
        # (user_id, (tuple of negative movie_ids))
        self.negatives_uri = os.path.join(get_project_dir(),
            "src/test/resources/data/ratings_train_disliked.array_record")
        
        self.recommendations_uri = os.path.join(get_project_dir(),
            "src/test/resources/data/recommended_movies.array_record")

        self.recommendations_ts_uri = os.path.join(get_project_dir(),
            "src/test/resources/data/recommended_movies_timestamps.array_record")
        
        self.ratings_train_uri = os.path.join(get_project_dir(),
            "src/test/resources/data/ratings_train_liked.array_record")
        
        self.ratings_train_uri_tiny = os.path.join(get_project_dir(),
            "src/test/resources/data/small/ratings_train_liked.array_record")
        
        self.ratings_test_uri = os.path.join(get_project_dir(),
            "src/test/resources/data/ratings_test_liked.array_record")
        
        self.movie_embeddings_uri = os.path.join(get_project_dir(),
            "src/test/resources/data/movie_emb-00000-of-00001.array_record")
        
        self.user_embeddings_uri = os.path.join(get_project_dir(),
            "src/test/resources/data/user_emb-00000-of-00001.array_record")
        
        self.movie_ids_uri = os.path.join(get_project_dir(),
            "src/test/resources/data/movies-00000-of-00001.array_record")

    def test_contracts(self):
        validate_movies(self.movie_ids_uri)
        validate_embedding(self.user_embeddings_uri)
        validate_embedding(self.movie_embeddings_uri)
        validate_movie_recommendations(self.recommendations_uri)
        validate_movie_recommendations_timestamps(self.recommendations_ts_uri)
        validate_ratings(self.negatives_uri)
        validate_ratings(self.ratings_train_uri)

    def test_embedding_exports(self):
        out_uri = os.path.join(get_bin_dir(), "schema_movie_emb.json")
        export_movie_embedding_contract(out_uri)
        assert os.path.exists(out_uri), "Contract JSON file was not created."
        assert os.path.isfile(out_uri), "Export path is not a valid file."

        with open(out_uri, "r", encoding="utf-8") as f:
            loaded_schema = json.load(f)

        # Verify core JSON Schema structure generated by Pydantic V2
        assert "properties" in loaded_schema
        assert "id" in loaded_schema["properties"]
        assert "embedding" in loaded_schema["properties"]

        # Direct parity check against Pydantic's live schema generation
        assert loaded_schema == MovieEmbeddingRecord.model_json_schema()

        #===========
        out_uri = os.path.join(get_bin_dir(), "schema_user_emb.json")
        export_user_embedding_contract(out_uri)
        assert os.path.exists(out_uri), "Contract JSON file was not created."
        assert os.path.isfile(out_uri), "Export path is not a valid file."

        with open(out_uri, "r", encoding="utf-8") as f:
            loaded_schema = json.load(f)

        # Verify core JSON Schema structure generated by Pydantic V2
        assert "properties" in loaded_schema
        assert "id" in loaded_schema["properties"]
        assert "embedding" in loaded_schema["properties"]

        # Direct parity check against Pydantic's live schema generation
        assert loaded_schema == UserEmbeddingRecord.model_json_schema()

    def test_movie_export(self):
        out_uri = os.path.join(get_bin_dir(), "schema_movie.json")
        export_movies_contract(out_uri)
        assert os.path.exists(out_uri), "Contract JSON file was not created."
        assert os.path.isfile(out_uri), "Export path is not a valid file."

        with open(out_uri, "r", encoding="utf-8") as f:
            loaded_schema = json.load(f)

        # Verify core JSON Schema structure generated by Pydantic V2
        assert "properties" in loaded_schema
        assert "movie_id" in loaded_schema["properties"]
        assert "title" in loaded_schema["properties"]
        assert "genres" in loaded_schema["properties"]

        # Direct parity check against Pydantic's live schema generation
        assert loaded_schema == MovieRecord.model_json_schema()

    def test_movie_recommendations_export(self):
        out_uri = os.path.join(get_bin_dir(), "schema_movie_rec.json")
        export_recommended_movies_contract(out_uri)
        assert os.path.exists(out_uri), "Contract JSON file was not created."
        assert os.path.isfile(out_uri), "Export path is not a valid file."

        with open(out_uri, "r", encoding="utf-8") as f:
            loaded_schema = json.load(f)

        # Verify core JSON Schema structure generated by Pydantic V2
        assert "properties" in loaded_schema
        assert "user_id" in loaded_schema["properties"]
        assert "movie_ids" in loaded_schema["properties"]

        # Direct parity check against Pydantic's live schema generation
        assert loaded_schema == RecommendedMoviesRecord.model_json_schema()

    def test_movie_recommendations_timestamps_export(self):
        out_uri = os.path.join(get_bin_dir(), "schema_movie_rec_ts.json")
        export_recommended_movies_timestamps_contract(out_uri)
        assert os.path.exists(out_uri), "Contract JSON file was not created."
        assert os.path.isfile(out_uri), "Export path is not a valid file."

        with open(out_uri, "r", encoding="utf-8") as f:
            loaded_schema = json.load(f)

        # Verify core JSON Schema structure generated by Pydantic V2
        assert "properties" in loaded_schema
        assert "user_id" in loaded_schema["properties"]
        assert "timestamps" in loaded_schema["properties"]

        # Direct parity check against Pydantic's live schema generation
        assert loaded_schema == RecommendedMoviesTimestampsRecord.model_json_schema()

    def test_ratings_export(self):
        out_uri = os.path.join(get_bin_dir(), "schema_rating.json")
        export_ratings_contract(out_uri)
        assert os.path.exists(out_uri), "Contract JSON file was not created."
        assert os.path.isfile(out_uri), "Export path is not a valid file."

        with open(out_uri, "r", encoding="utf-8") as f:
            loaded_schema = json.load(f)

        # Verify core JSON Schema structure generated by Pydantic V2
        assert "properties" in loaded_schema
        assert "user_id" in loaded_schema["properties"]
        assert "movie_id" in loaded_schema["properties"]
        assert "rating" in loaded_schema["properties"]
        assert "timestamp" in loaded_schema["properties"]

        # Direct parity check against Pydantic's live schema generation
        assert loaded_schema == RatingsRecord.model_json_schema()

if __name__ == '__main__':
    unittest.main()
