#USAGE
#  docker compose --project-directory . -f deploy/compose/docker-compose-TFS-dont-use.yaml up -d
#     the project_directory flag ensure the file paths are all relative to that directory
services:
  bi-encoder:
    #24.xx containers for TF 2.16.1
    # image is nearly 10GB in size so first pull might take several minutes.
    image: nvcr.io/nvidia/tritonserver:24.12-py3
    container_name: bi-encoder
    restart: unless-stopped
    ports:
      - "172.17.0.1:8500:8000" # HTTP
      - "172.17.0.1:8501:8001" # GRPC
      - "172.17.0.1:8502:8002" # metrics, prometheus
    environment:
      - MODEL_NAME=two-tower
    volumes:
      - ./src/test/resources/model_repositories/bi-encoder:/models/
    command: [ "tritonserver", "--model-repository=/models" ]
    healthcheck:
      # Triton has a built-in health endpoint
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v2/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 3

  cross-encoder:
    # 26.xx containers for jax 0.8.*
    # 26.03 through 26.06
    # image is nearly 10GB in size so first pull might take several minutes
    image: nvcr.io/nvidia/tritonserver:26.04-py3
    container_name: cross-encoder
    restart: unless-stopped
    ports:
      - "172.17.0.1:8510:8000" # HTTP
      - "172.17.0.1:8511:8001" # gRPC
      - "172.17.0.1:8512:8002" # metrics, prometheus
    environment:
      - MODEL_NAME=graph-ranker
    volumes:
      - ./src/test/resources/model_repositories/cross-encoder:/models/
    command: [ "tritonserver", "--model-repository=/models" ]
    healthcheck:
      # Triton has a built-in health endpoint
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v2/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 3