services:
  bi-encoder:
    #24.xx containers for TF 2.16.1
    # image is nearly 10GB in size so first pull might take several minutes.
    image: nvcr.io/nvidia/tritonserver:24.12-py3
    container_name: bi-encoder
    restart: unless-stopped
    ports:
      - "172.17.0.1:8500:8000" # gRPC port
      - "172.17.0.1:8501:8001" # REST API port
      - "172.17.0.1:8502:8002" # metrics
    environment:
      - MODEL_NAME=two-tower
    volumes:
      - ./src/test/resources/model_repositories/bi-encoder:/models/
    command: [ "tritonserver", "--model-repository=/models" ]
    healthcheck:
      # Triton has a built-in health endpoint
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v2/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 3
