include:
   - path: ./deploy/compose/docker-compose-dbs.yaml
     project_directory: .
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_cpu
    image: ranker-app:local
    container_name: ranker-app
    depends_on:
      db:
        condition: service_healthy
      gcs:
        condition: service_healthy
      vizier-server:
        condition: service_healthy
    env_file:
      - .env
    user: "${UID_DB}:${GID_DB}"
    volumes:
      #avoid rebuilding when src code changes:
      - ./src:/app/src
    environment:
      #- PYTHONPATH=/usr/local/lib/python3.11/site-packages
      #these are in .env
      - LOGNAME=${POSTGRES_USER}
      - USER=${POSTGRES_USER}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GCSFS_ENDPOINT_URL=${GCSFS_ENDPOINT_URL}
      #- TENSORSTORE_GCS_HTTP_ENDPOINT=${TENSORSTORE_GCS_HTTP_ENDPOINT}
      - STORAGE_EMULATOR_HOST=${STORAGE_EMULATOR_HOST}
      - CLOUD_STORAGE_EMULATOR_HOST=${CLOUD_STORAGE_EMULATOR_HOST}
      - CLOUD_STORAGE_EMULATOR_ENDPOINT=${CLOUD_STORAGE_EMULATOR_ENDPOINT}
      - TENSORSTORE_GCS_NO_AUTH=${TENSORSTORE_GCS_NO_AUTH}
      - NO_GCE_CHECK=${NO_GCE_CHECK}
      - GCS_LAMBDA_TOKEN=${GCS_LAMBDA_TOKEN}
      - GOOGLE_AUTH_SUPPRESS_CREDENTIALS_WARNINGS=${GOOGLE_AUTH_SUPPRESS_CREDENTIALS_WARNINGS}
      - STORAGE_EMULATOR_HOST_HTTP=${STORAGE_EMULATOR_HOST_HTTP}
      - GOOGLE_AUTH_EXTERNAL_ACCOUNT_TOKEN_PROHIBIT=${GOOGLE_AUTH_EXTERNAL_ACCOUNT_TOKEN_PROHIBIT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - NUMBA_CACHE_DIR=/tmp/numba_cache
