//! class to prepare inputs into protocol buffers for use in gRPC calls to a Tensorflow Serving or other server
//! hosting the TF SavedModel
use std::error::Error;
use std::fs::Metadata;
use crate::graph_builder::{build_enriched_padded_supergraph, JraphGraph};
use once_cell::sync::Lazy;

use std::collections::HashMap;
use tonic::transport::Channel;

//use crate::inference::tf_core::Example;

// Inject the code generated by build.rs
pub mod tf_serving {
    tonic::include_proto!("tensorflow.serving");
}
pub mod tf_core {
    tonic::include_proto!("tensorflow");
}
// keep these here to put them in scope for the compiler
use tf_core::Example;
use tf_core::SignatureDef;

use tf_serving::prediction_service_client::PredictionServiceClient;
use tf_serving::{PredictRequest, ModelSpec, PredictResponse};
use tf_core::{TensorProto, TensorShapeProto, DataType};
use tf_core::tensor_shape_proto::Dim;
use crate::user_history::{build_user_history, UserHistory};


// the trained model has a fixed max_history and num_candidates.
// ideally, we would read it from the model metadata, but for now, we will use
// constants for them.  These would have to be versions, along with signatures...
// update after HPO finds best.
const MAX_HISTORY : usize = 40;
const NUM_CANDIDATES : usize = 50;
const TFS_ENDPOINT : &str = "http://localhost:8500";


// Define the Trait
pub trait IntoTensorProto {
    fn into_tensor(self) -> TensorProto;
}

// Implement for Vec<i32> (For nodes, edges, senders, receivers)
impl IntoTensorProto for Vec<i32> {
    fn into_tensor(self) -> TensorProto {
        let size = self.len() as i64;
        TensorProto {
            dtype: DataType::DtInt32 as i32,
            tensor_shape: Some(TensorShapeProto {
                dim: vec![Dim { size, name: String::new() }],
                unknown_rank: false,
            }),
            version_number: 0,
            int_val: self, // Pack the data here
            // ... all other fields must be empty vectors
            tensor_content: vec![], half_val: vec![], float_val: vec![],
            double_val: vec![], string_val: vec![], scomplex_val: vec![],
            int64_val: vec![], bool_val: vec![], dcomplex_val: vec![],
            resource_handle_val: vec![], variant_val: vec![],
            uint32_val: vec![], uint64_val: vec![],
            float8_val: vec![],
        }
    }
}

// Implement for Vec<bool> (For candidate masks)
impl IntoTensorProto for Vec<bool> {
    fn into_tensor(self) -> TensorProto {
        let size = self.len() as i64;
        TensorProto {
            dtype: DataType::DtBool as i32,
            tensor_shape: Some(TensorShapeProto {
                dim: vec![Dim { size, name: String::new() }],
                unknown_rank: false,
            }),
            version_number: 0,
            bool_val: self, // Pack the bools here
            // ... empty out the rest just like above
            tensor_content: vec![], half_val: vec![], float_val: vec![],
            double_val: vec![], int_val: vec![], string_val: vec![], scomplex_val: vec![],
            int64_val: vec![], dcomplex_val: vec![], resource_handle_val: vec![],
            variant_val: vec![], uint32_val: vec![], uint64_val: vec![],
            float8_val: vec![],
        }
    }
}

#[tokio::main]
pub async fn run_inference(
    savedmodel_uri: &str,
    user_ids: &[i32],
    timestamps: &[i64],
    candidate_ids: &[i32],
    ratings_uris : &[&str],
) -> Result<(Vec<f32>), Box<dyn Error>> {

    if candidate_ids.len() != NUM_CANDIDATES {
        panic!["candidates length should be {}", NUM_CANDIDATES]
    }

    if user_ids.len() != timestamps.len() {
        panic!["user_ids length should equal timestamps length"]
    }

    // create padded_super_graph
    let user_history : UserHistory = build_user_history(&ratings_uris, 2048);


    //labels aren't used in inference.  a value of -1 can help distinguish that is isn't used.
    let labels: Vec<i32> = vec![-1; candidate_ids.len()];

    let n_loal_devices_on_server = 1;
    let padded_super_graph : JraphGraph = build_enriched_padded_supergraph(&user_ids, &timestamps,
        &candidate_ids, &labels, &user_history, MAX_HISTORY, n_loal_devices_on_server);

    let inputs : HashMap<String, TensorProto> = build_proto_inputs(padded_super_graph);

    let mut client = PredictionServiceClient::connect(TFS_ENDPOINT).await?;

    // Define which model and signature
    let model_spec = ModelSpec {
        name: "movie_lens_ranker".into(),
        signature_name: "serving_default".into(),
        version_choice: None,
    };

    let request = tonic::Request::new(PredictRequest {
        model_spec: Some(model_spec),
        inputs,
        output_filter: Vec::new(),
        predict_streamed_options: None,
        client_id: None,
        request_options: None,
    });

    println!("Sending gRPC request to TF Serving...");

    let response = client.predict(request).await?;

    /*
    the question mark at the end of the await is symbol for:
    let response = match client.predict(request).await {
        Ok(resp) => resp,
        Err(status) => {
            // If TF Serving throws an error, the ? operator IMMEDIATELY
            // stops this function and returns the error to the caller.
            return Err(status.into());
        }
    };
    */

    // Make inner_response mutable so we can consume its fields
    let mut inner_response = response.into_inner();

    // Use .remove() instead of .get() to take ownership of the vector
    if let Some(output_tensor) = inner_response.outputs.remove("output_0") {
        // float_val is already a Vec<f32>, so we just return it
        Ok(output_tensor.float_val)
    } else {
        // Return a boxed error string if the key doesn't exist
        Err("Error: 'output_0' not found in TF Serving response".into())
    }

}

fn build_proto_inputs(padded_super_graph: JraphGraph) -> HashMap<String, TensorProto> {
    /*
    //MAX_GRAPHS:
    padded_super_graph.n_node
    padded_super_graph.n_edge
    //MAX_EDGES:
    padded_super_graph.senders
    padded_super_graph.receivers
    padded_super_graph.edge_features
    //MAX_NODES:
    padded_super_graph.node_ids
    padded_super_graph.node_labels
    padded_super_graph.node_types
    padded_super_graph.candidate_mask
    */
    let mut inputs = HashMap::new();

    // Graph Structure (Usually single-element Vecs or small arrays)
    inputs.insert("n_node".into(), padded_super_graph.n_node.into_tensor());
    inputs.insert("n_edge".into(), padded_super_graph.n_edge.into_tensor());

    // Connectivity & Edge Features
    inputs.insert("senders".into(), padded_super_graph.senders.into_tensor());
    inputs.insert("receivers".into(), padded_super_graph.receivers.into_tensor());
    inputs.insert("edge_features".into(), padded_super_graph.edge_features.into_tensor());

    // Node Features
    inputs.insert("node_ids".into(), padded_super_graph.node_ids.into_tensor());
    inputs.insert("node_labels".into(), padded_super_graph.node_labels.into_tensor());
    inputs.insert("node_types".into(), padded_super_graph.node_types.into_tensor());

    // Masks
    inputs.insert("candidate_mask".into(), padded_super_graph.candidate_mask.into_tensor());

    inputs
}

